### ISSUE TITLE
New Feature Request: Display "nvddl.exe" Version Number

### ISSUE THREAD

**Issue by valsamis-d** [Aetopia/NVIDIA-Driver-Downloader#10]
Hello @Aetopia 

Would it be too much work for you to display somewhere the version number of "nvddl.exe", when, for example, it is executed without any arguments?

![image](https://user-images.githubusercontent.com/17590539/180221247-ff2990ba-2209-46f1-b05c-231b554d51f7.png)

Thank you
Dimitrios

**Comment by Aetopia** [comment]
Will be added!
