### ISSUE TITLE
Suggestion for the syntax of the arguments

### ISSUE THREAD

**Issue by UltraToon** [Aetopia/NVIDIA-Driver-Downloader#2]
Try changing the multi letter arguments with a double dash at the start (for eg., "--download") and you can use for the single letter arguments, "-d" (for download). 

This is usually a quality of life tweak for it, I only recommended this because a lot of programs do this with their argument syntax.

**Comment by Aetopia** [comment]
Will be added!

**Comment by Aetopia** [comment]
### Added with [v1.1.0](https://github.com/Aetopia/NVIDIA-Driver-Downloader/tree/v1.1.0)!
