### ISSUE TITLE
Improvements - Multilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [Aetopia/NVIDIA-Driver-Downloader#6]
@Aetopia 

Thanks for the tool.

Could you pelase condier for next relase to have a multilanguage GUI?

Could create an external language file and use differnt language file for each language.

Thanks.

**Comment by Aetopia** [comment]
If you want a multi-language tool, consider using `NVCleanInstall`.
NVDDL is meant to be pure CLI tool for downloading NVIDIA Drivers, but feel free to make your own GUI wrapper.

**Comment by bovirus** [comment]
Aetopia

Using Python (base of your tool) is quite simple make the application multilanguage.

**Comment by Aetopia** [comment]
Problem isn't making the GUI, problem is maintaining multiple languages and implementing them.

I will not be considering this but thank you for suggestion!

**Comment by bovirus** [comment]
@Ateopia

You job is aonly to modify the source and make available an external language with all strings.
And you have only to maintain english master language.
Provide you/maintain a trsnaltion in other language is not your job but by translators.

**Comment by Aetopia** [comment]
1. I am not interested to make a GUI.
2. Adding Multi-language support is not a priority for this project.
3. Problem with maintaining with multiple languages is that if I need to update the language files, then that would require me to contact the respective translators.

**Comment by Aetopia** [comment]
> @Aetopia
> 
> 1. I'm afraid that you are not interested
> 2. Not a priority now not means the same for the future
> 3. Is not neecssary to contact the translators. If they don't improve teh translations it remain in english.

I don't see the point of adding a GUI, its suppose to a CLI tool only.
