### ISSUE TITLE
Add Quadro/RTX Card Support.

### ISSUE THREAD

**Issue by valsamis-d** [Aetopia/NVIDIA-Driver-Downloader#7]
This occurs in the latest release v1.3.4.3. See below:

![image](https://user-images.githubusercontent.com/17590539/177533631-6d320171-759e-4b56-abf6-c51cb188a0dd.png)

**Comment by Aetopia** [comment]
Would also mind sending, which Windows Version, you are running.

**Comment by valsamis-d** [comment]
@Aetopia I'm running Windows 10 Enterprise (21H2 19044.1766)

Here are the contents of Log File:

`INFO: Namespace: Namespace(list=True, download=None, extract=None, update=False, studio=False, standard=False, full=False, setup=False, components=[], output='F:\\Temp\\DVALSA~1', flags=[], no_stdout=False)
INFO: Arguments: ['nvddl.exe', '--list']
INFO: Getting Driver Versions...
INFO: Selected Driver Type: Game Ready
INFO: Selected Driver Type: DCH
INFO: Detected: Quadro P1000
INFO: API Link Generated: https://www.nvidia.com/Download/processFind.aspx?psid=543&pfid=874&osid=57&lid=1&whql=1&ctk=0&dtcid=1
INFO: Finished!
`
And also the Error Traceback File:

`Traceback (most recent call last):
  File "F:\Temp\DVALSA~1\ONEFIL~1\main.py", line 180, in <module>
  File "F:\Temp\DVALSA~1\ONEFIL~1\main.py", line 171, in main
  File "F:\Temp\DVALSA~1\ONEFIL~1\functions.py", line 142, in download
  File "F:\Temp\DVALSA~1\ONEFIL~1\urllib\request.py", line 216, in urlopen
  File "F:\Temp\DVALSA~1\ONEFIL~1\urllib\request.py", line 519, in open
  File "F:\Temp\DVALSA~1\ONEFIL~1\urllib\request.py", line 536, in _open
  File "F:\Temp\DVALSA~1\ONEFIL~1\urllib\request.py", line 496, in _call_chain
  File "F:\Temp\DVALSA~1\ONEFIL~1\urllib\request.py", line 1391, in https_open
  File "F:\Temp\DVALSA~1\ONEFIL~1\urllib\request.py", line 1348, in do_open
  File "F:\Temp\DVALSA~1\ONEFIL~1\http\client.py", line 1282, in request
  File "F:\Temp\DVALSA~1\ONEFIL~1\http\client.py", line 1293, in _send_request
  File "F:\Temp\DVALSA~1\ONEFIL~1\http\client.py", line 1127, in putrequest
  File "F:\Temp\DVALSA~1\ONEFIL~1\http\client.py", line 1227, in _validate_path
http.client.InvalidURL: URL can't contain control characters. '/Windows/R515 U2 (516.59)/R515 U2 (516.59)-notebook-win10-win11-64bit-international-dch-whql.exe' (found at least ' ')
`

**Comment by Aetopia** [comment]
It seems NVDDL, isn't able to parse the link: `https://www.nvidia.com/Download/processFind.aspx?psid=543&pfid=874&osid=57&lid=1&whql=1&ctk=0&dtcid=1`

**Comment by valsamis-d** [comment]
@Aetopia hi,

The issue perrsists in "v1.4.0 Pre-Release 1"

Thank you
Dimitrios

**Comment by Aetopia** [comment]
> @Aetopia hi,
> 
> The issue persists in "v1.4.0 Pre-Release 1"
> 
> Thank you Dimitrios

Yeh, since I didn't add version parsing yet.

**Comment by valsamis-d** [comment]
> > @Aetopia hi,
> 
> > 
> 
> > The issue persists in "v1.4.0 Pre-Release 1"
> 
> > 
> 
> > Thank you Dimitrios
> 
> 
> 
> Yeh, since I didn't add version parsing yet.

Oops... I didn't mean to push you. I just thought you might want to know 😉

**Comment by Aetopia** [comment]
> > > @Aetopia hi,
> > 
> > 
> > > 
> > 
> > 
> > > The issue persists in "v1.4.0 Pre-Release 1"
> > 
> > 
> > > 
> > 
> > 
> > > Thank you Dimitrios
> > 
> > 
> > Yeh, since I didn't add version parsing yet.
> 
> Oops... I didn't mean to push you. I just thought you might want to know 😉

I added some pretty basic detection, incase if the version number isn't float, its gonna switch to Quadro links.

**Comment by Aetopia** [comment]
Check the newest release.

**Comment by valsamis-d** [comment]
> Check the newest release.

See below:

![image](https://user-images.githubusercontent.com/17590539/179345870-23c642dd-7b29-4f28-90a1-89558d67c91a.png)

Contents of "_%TEMP%\nvddl.log_"

```
INFO: Namespace: Namespace(list=False, download=None, extract=None, update=True, studio=False, standard=False, full=False, setup=False, components=[], output='F:\\Temp\\DVALSA~1', flags=[], no_stdout=False)
INFO: Arguments: ['nvddl.exe', '-u']
INFO: Updating Driver...
INFO: Selected Driver Type: Game Ready
INFO: Selected Driver Type: DCH
INFO: Detected: GP107GLM [Quadro P1000 Mobile]
INFO: API Link Generated: https://www.nvidia.com/Download/processFind.aspx?psid=543&pfid=874&osid=57&lid=1&whql=1&ctk=0&dtcid=1
ERROR: Found an uncatchable exception!
ERROR: Exception: invalid syntax (<unknown>, line 1)
INFO: Exiting...
```

Contents of "%TEMP%\nvddl_traceback.txt":

```
Traceback (most recent call last):
  File "F:\Temp\DVALSA~1\ONEFIL~2\main.py", line 180, in <module>
  File "F:\Temp\DVALSA~1\ONEFIL~2\main.py", line 153, in main
  File "F:\Temp\DVALSA~1\ONEFIL~2\functions.py", line 256, in update
  File "F:\Temp\DVALSA~1\ONEFIL~2\ast.py", line 62, in literal_eval
  File "F:\Temp\DVALSA~1\ONEFIL~2\ast.py", line 50, in parse
  File "<unknown>", line 1
    R515 U2 (516.59)
         ^^
SyntaxError: invalid syntax
```

**Comment by Aetopia** [comment]
Which pre-release version are you running?

**Comment by valsamis-d** [comment]
@Aetopia just tested with ""NVIDIA Driver Downloader v1.4.0 Pre-Release 3" :

![image](https://user-images.githubusercontent.com/17590539/179353818-b6562764-d72b-4a3e-8a3f-6c5471570a1c.png)

Contents of "_%TEMP%\nvddl.log_"

```
INFO: Namespace: Namespace(list=False, download=None, extract=None, update=True, studio=False, standard=False, full=False, setup=False, components=[], output='F:\\Temp\\DVALSA~1', flags=[], no_stdout=False)
INFO: Arguments: ['nvddl.exe', '-u']
INFO: Updating Driver...
INFO: Selected Driver Type: Game Ready
INFO: Selected Driver Type: DCH
INFO: Detected: GP107GLM [Quadro P1000 Mobile]
INFO: API Link Generated: https://www.nvidia.com/Download/processFind.aspx?psid=543&pfid=874&osid=57&lid=1&whql=1&ctk=0&dtcid=1
ERROR: Found an uncatchable exception!
ERROR: Exception: invalid syntax (<unknown>, line 1)
INFO: Exiting...
```

Contents of "_%TEMP%\nvddl_traceback.txt_":

```
Traceback (most recent call last):
  File "F:\Temp\DVALSA~1\ONEFIL~2\main.py", line 180, in <module>
  File "F:\Temp\DVALSA~1\ONEFIL~2\main.py", line 153, in main
  File "F:\Temp\DVALSA~1\ONEFIL~2\functions.py", line 230, in update
  File "F:\Temp\DVALSA~1\ONEFIL~2\ast.py", line 62, in literal_eval
  File "F:\Temp\DVALSA~1\ONEFIL~2\ast.py", line 50, in parse
  File "<unknown>", line 1
    R515 U2 (516.59)
         ^^
SyntaxError: invalid syntax
```

**Comment by Aetopia** [comment]
```py
try: 
    float(driver_version)
except ValueError:
    driver_version = driver_version.split('(')[1].strip(')').strip()
```
I had to offload the `fix` to the `get_driver_versions` function instead.
https://user-images.githubusercontent.com/41850963/179353957-11728428-be8d-4a4b-ba43-e3852f333726.mp4

**Comment by Aetopia** [comment]
Now instead of displaying `R515 U2 (516.59)` it should display `516.59`.

**Comment by valsamis-d** [comment]
@Aetopia glad you found it! Hope I helped you with providing complete feedback. I will be waiting for the new binary version, as what you have in the video is Chinese to me. No offense to Chinese people, it's just that I'm Greek so the saying 'Greek to me' would not make sense :)

**Comment by Aetopia** [comment]
> @Aetopia glad you found it! Hope I helped you with providing complete feedback. I will be waiting for the new binary version, as what you have in the video is Chinese to me. No offense to Chinese people, it's just that I'm Greek so the saying 'Greek to me' would not make sense :)

Um, its not chinese....
Its the source code.

**Comment by valsamis-d** [comment]
@Aetopia just tested it and is working like a charm! Thank you so much!

![image](https://user-images.githubusercontent.com/17590539/179354557-40b3b366-8945-4d3d-95e4-11dfc2267b1b.png)

**Comment by Aetopia** [comment]
Anything else, you need? Or I can close this?

**Comment by valsamis-d** [comment]
No, thank you! You can go ahead and close it.
