### ISSUE TITLE
nvddl.exe --download error

### ISSUE THREAD

**Issue by valsamis-d** [Aetopia/NVIDIA-Driver-Downloader#8]
Tested this with the latest version and got the following error:

![image](https://user-images.githubusercontent.com/17590539/177537239-fa9cfa6b-6f11-4d23-a0bb-2ce5405089dd.png)

**Comment by valsamis-d** [comment]
@Aetopia just out of curiosity, did you close this as a duplicate of "_Add Quadro/RTX Card Support. #7_" ?

**Comment by Aetopia** [comment]
> @Aetopia just out of curiosity, did you close this as a duplicate of "_Add Quadro/RTX Card Support. #7_" ?

Yes.
